name: horda_server
description: Stateful serverless backend for Flutter apps
version: 0.16.0
homepage: https://github.com/horda-ai/dart_server

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  horda_core: ^0.15.0
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
